// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igwqgcrsjtaesuniswfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlnd3FnY3JzanRhZXN1bmlzd2Z3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMTc0NjksImV4cCI6MjA3MTc5MzQ2OX0.1Ai20hSqr8B7Z-m45nAQCIWjuU4eghnzwMyND4kIlLc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});